name: pdfrx_engine
description: pdfrx_engine is a PDF rendering and manipulation API built on top of PDFium, designed to be used with the pdfrx plugin. Supports viewing, editing, and combining PDF documents.
version: 0.4.5
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfrx_engine
issue_tracker: https://github.com/espresso3389/pdfrx/issues

environment:
  sdk: ^3.10.0
resolution: workspace

# Some of the dependencies are intentionally not pinned to a specific version
# to allow for more flexibility in resolving versions when used in larger projects.
dependencies:
  pdfium_dart: ^0.2.5
  collection:
  crypto:
  ffi: ^2.2.0
  http:
  meta:
  path: ^1.9.1
  rxdart:
  synchronized:
  vector_math:
  archive:
  image: ^4.8.0

dev_dependencies:
  lints:
  test:
