name: pdfium_flutter
description: Flutter FFI plugin for PDFium integration on Android, iOS, Windows, macOS, and Linux.
version: 0.2.0
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfium_flutter
issue_tracker: https://github.com/espresso3389/pdfrx/issues

environment:
  sdk: ^3.10.0
  flutter: ">=3.41.0"
resolution: workspace

dependencies:
  pdfium_dart: ^0.2.0
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
