name: Build and release PDFium binaries for iOS and macOS
on:
  push:
    tags:
      - pdfium-apple-*
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ios, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build PDFium ${{ matrix.target }}
        run: ./packages/pdfrx/darwin/pdfium/build ${{ matrix.target }}
      - name: Upload PDFium artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: pdfium-${{ matrix.target }}
          path: ./packages/pdfrx/darwin/pdfium/pdfium-${{ matrix.target }}.zip

  release:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download iOS artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6.0.0
        with:
          name: pdfium-ios
          path: ./packages/pdfrx/darwin/pdfium/
      - name: Download macOS artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6.0.0
        with:
          name: pdfium-macos
          path: ./packages/pdfrx/darwin/pdfium/
      - name: Release PDFium
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v0.1.15
        with:
          token: ${{ secrets.TOKEN_FOR_RELEASE }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: iOS/macOS PDFium prebuilt binary distribution for pdfrx (${{ github.ref_name }}).
          files: |
            ./packages/pdfrx/darwin/pdfium/pdfium-ios.zip
            ./packages/pdfrx/darwin/pdfium/pdfium-macos.zip
